general.import = [
  "./catppuccin-mocha.toml"
]

[window]
padding.x = 10
padding.y = 10
# opacity = 0.95

[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u001b[1;5D"

[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u001b[1;5C"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }
size = 12.0
